# Generated by Django 5.1.7 on 2025-03-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_userfollowing_user_following'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('to_user', 'from_user')},
        ),
    ]
